project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  navbar:
    left:
        - href: Home
        - max.qmd
        - addition.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
